export const DATASETS = [
  {
    name: "GazeMining",
    tag: "WEB CONTENT",
    content: "Browser recordings, gaze, frame timestamps and DOM observations.",
    input: "Stimulus + gaze",
    use: "Replay, scrolling, dynamic AOIs",
    license:
      "Repository declares CC0; third-party page content retains its rights.",
    access: "Direct download · working sample included",
    url: "https://zenodo.org/records/5031618",
  },
  {
    name: "EVE",
    tag: "WEBCAM BENCHMARK",
    content: "Synchronized face cameras, screen recordings and reference gaze.",
    input: "Face + stimulus + gaze",
    use: "RGB model evaluation, temporal refinement",
    license: "CC BY-NC-SA 4.0 + additional terms",
    access: "Access request required",
    url: "https://ait.ethz.ch/eve",
  },
  {
    name: "GazeCom",
    tag: "NATURAL VIDEO",
    content:
      "Natural movie viewing with fixation, saccade and pursuit annotations.",
    input: "Stimulus + gaze + event labels",
    use: "Event detection, saliency and scanpaths",
    license:
      "Annotations repository has GPL; review original stimulus terms separately.",
    access:
      "ARFF download available; original video host unavailable in our check",
    url: "https://michaeldorr.de/smoothpursuit/",
  },
  {
    name: "DIEM",
    tag: "DYNAMIC SCENES",
    content:
      "Movie clips and participant gaze, with CARPE visualization exports.",
    input: "Stimulus + gaze",
    use: "Video attention and comparative replay",
    license: "Check per-stimulus rights before redistribution",
    access: "Public video/data links",
    url: "https://thediemproject.wordpress.com/videos-and%C2%A0data/",
  },
  {
    name: "BIDS eye tracking example",
    tag: "FORMAT REFERENCE",
    content:
      "Natural-image free viewing with per-eye physiological recordings.",
    input: "BIDS physio + stimulus events",
    use: "Interoperability and sidecar validation",
    license: "Consult repository dataset_description and original data terms",
    access: "Public repository · Git LFS data",
    url: "https://github.com/julia-pfarr/natImSac_BIDSexample",
  },
  {
    name: "Focus100",
    tag: "DRIVING",
    content: "Anonymized driving videos, individual gaze and YOLO detections.",
    input: "Stimulus + gaze + boxes",
    use: "Dynamic object AOIs and attention",
    license: "CC BY-NC-SA 4.0; academic access only",
    access: "Restricted · manual review",
    url: "https://huggingface.co/datasets/GlimpseML/Focus100",
  },
  {
    name: "GazeBase",
    tag: "SIGNAL ANALYSIS",
    content: "High-rate gaze recordings across multiple viewing tasks.",
    input: "Gaze in degrees of visual angle",
    use: "Signal quality, events and biometrics",
    license: "See dataset record; movie stimulus rights are separate",
    access: "Public research dataset",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8285447/",
  },
  {
    name: "Pupil Neon sample",
    tag: "WEARABLE",
    content:
      "World video, native sensor recordings and exportable gaze streams.",
    input: "Scene + gaze + frame clock",
    use: "Scene-camera replay and import testing",
    license: "Verify sample redistribution terms; native code licenses differ",
    access: "Official sample download",
    url: "https://docs.pupil-labs.com/neon/neon-player/getting-started/",
  },
  {
    name: "MPIIGaze",
    tag: "GAZE ESTIMATION",
    content: "Laptop eye images, gaze directions and camera calibration.",
    input: "Eye images + labels",
    use: "Cross-person angular error; not stimulus replay",
    license: "Dataset use terms apply",
    access: "Research download",
    url: "https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/appearance-based-gaze-estimation-in-the-wild",
  },
  {
    name: "ETH-XGaze",
    tag: "GAZE ESTIMATION",
    content: "Multi-camera images spanning large head-pose and gaze ranges.",
    input: "Face images + gaze labels",
    use: "Pose robustness and angular benchmarks",
    license: "Dataset license and access terms apply",
    access: "Research access request",
    url: "https://ait.ethz.ch/xgaze",
  },
];
